/**
 * 초기 게임 상태 팩토리
 * gameStore.ts와 saveSlice.ts 양쪽에서 import — 순환 의존성 없음
 */
import { BALANCE_PARAMS } from '../data/balance';
import type { GameState } from './types';
import { INITIAL_BAHWAGYO_STATE } from './slices/bahwagyoSlice';

const B = BALANCE_PARAMS;

export function createInitialState(): GameState {
  return {
    qi: 0,
    totalSpentQi: 0,
    stats: { gi: 0, sim: 0, che: 0 },
    proficiency: { sword: 1, palm: 1, footwork: 1, mental: 1, fist: 1 },
    hp: B.HP_BASE,
    maxHp: B.HP_BASE,
    tier: 0,
    selectedProfileKey: null,
    customProfileUrl: null,

    stamina: 0,
    ultCooldowns: {},
    currentBattleDuration: 0,
    currentBattleDamageDealt: 0,
    currentBattleDamageTaken: 0,
    currentBattleCritCount: 0,
    currentBattleDodgeCount: 0,
    currentBattleHitTakenCount: 0,
    currentBattleMaxOutgoingHit: 0,
    currentBattleMaxIncomingHit: 0,
    currentBattleSkillUseCount: 0,

    sessionFieldId: null,
    sessionStartedAt: 0,
    sessionKills: 0,
    sessionQiGained: 0,
    sessionTotalDamage: 0,
    sessionActiveTime: 0,
    sessionMaxDps: 0,
    sessionBattleWins: 0,
    sessionDeaths: 0,
    sessionDrops: {},
    sessionProfGains: {},

    equippedSimbeop: null,
    ownedArts: [],
    equippedArts: [],
    artPoints: 3,
    artGradeExp: {},
    currentField: null,
    battleMode: 'none',
    huntTarget: null,
    pendingHuntRetry: false,
    pendingAutoExplore: false,
    currentEnemy: null,
    exploreStep: 0,
    exploreOrder: [],
    isBossPhase: false,
    bossTimer: 0,
    explorePendingRewards: { drops: [], proficiencyGains: {}, materialDrops: {} },
    battleLog: [],
    combatElapsed: 0,
    logEntryIdSeq: 0,
    lawActiveFromSkillId: null,
    playerAttackTimer: 0,
    enemyAttackTimer: 0,
    achievements: [],
    achievementCount: 0,
    killCounts: {},
    bossKillCounts: {},
    totalYasanKills: 0,
    totalKills: 0,
    totalSeonghwaUsed: 0,
    seonghwaRewardsClaimed: 0,
    hiddenRevealedInField: {},
    firstEnteredFields: {},
    bossPatternState: null,
    playerStunTimer: 0,
    lastEnemyAttack: null,
    baehwagyoEmberTimer: 0,
    baehwagyoAshOathBuffs: [],
    baehwagyoMukneomBurnCounter: 0,
    baehwagyoMukneomDmgReductBuff: null,
    sarajinunBulggotTimer: 0,
    tamsikKillStacks: {},
    tamsikEmberStacks: 0,
    lastConsumableResult: null,
    pendingReveal: null,
    tutorialFlags: {
      equippedSword: false,
      equippedSimbeop: false,
      yasanUnlocked: false,
      killedWood: false,
      killedIron: false,
      firstBreakthroughNotified: false,
    },
    lastTickTime: Date.now(),
    monotonicNow: Date.now(),
    lastOfflineRewardAt: 0,
    battleResult: null,
    floatingTexts: [],
    nextFloatingId: 0,
    playerAnim: '',
    enemyAnim: '',
    activeMasteries: {},
    gameSpeed: 1,
    paused: false,
    currentSaveSlot: 0,
    fieldUnlocks: {
      training: true,
      yasan: false,
      inn: false,
      cheonsan_jangmak: false,
      cheonsan_godo: false,
      cheonsan_simjang: false,
      baehwagyo_oemun: false,
      baehwagyo_naemun: false,
      baehwagyo_sawon: false,
      baehwagyo_simcheo: false,
    },
    inventory: [],
    discoveredMasteries: [],
    pendingEnlightenments: [],
    equipment: { weapon: null, armor: null, gloves: null, boots: null },
    equipmentInventory: [],
    materials: {},
    equipmentDotOnEnemy: [],
    craftedRecipes: [],
    unlockedRecipes: [],
    obtainedMaterials: [],
    knownEquipment: [],
    dodgeCounterActive: false,
    autoExploreFields: {},
    repeatableAchCounts: {},
    bahwagyo: INITIAL_BAHWAGYO_STATE,
  };
}
